PRAGMA foreign_keys = ON;

-- ── Labels ──────────────────────────────────────────────────────────────────
INSERT INTO labels (name, color) VALUES
    ('api', '#2563eb'),
    ('frontend', '#0891b2'),
    ('bug', '#dc2626'),
    ('good-first-issue', '#16a34a'),
    ('needs-discussion', '#ca8a04'),
    ('database', '#7c3aed'),
    ('auth', '#db2777'),
    ('performance', '#ea580c'),
    ('docs', '#0d9488'),
    ('ui', '#9333ea'),
    ('testing', '#475569'),
    ('security', '#b91c1c'),
    ('blocked', '#737373'),
    ('wontfix', '#525252'),
    ('devops', '#0284c7'),
    ('ux', '#d946ef'),
    ('refactor', '#84cc16'),
    ('mobile', '#06b6d4'),
    ('accessibility', '#f97316'),
    ('technical-debt', '#a1a1aa');

-- ── Issues (100+) ────────────────────────────────────────────────────────────
INSERT INTO issues (title, description, status, priority, issue_type, assignee, created_by) VALUES
-- 1-10: Bugs
('Multipart upload fails for large screenshots',
 'Uploading a 5MB png returns a 500 with no body. Expected: a clean 413 with a JSON error, or success within the configured limit. Repro: POST /issues/1/attachments with a 5MB image — server logs show "PayloadTooLarge" but the error is not surfaced to the client.',
 'open', 'high', 'bug', 'Tanner', 'Jason'),
('Comment ordering is inconsistent across reloads',
 'Comments sometimes render newest-first, sometimes oldest-first. Suspect the API is not specifying ORDER BY. Confirmed: the query is SELECT * FROM comments WHERE issue_id = ?. No ORDER BY clause.',
 'open', 'high', 'bug', 'Mason', 'Tanner'),
('XSS in comment body rendering',
 'Comment bodies are inserted with dangerouslySetInnerHTML. A comment containing <script> executes. Needs a sanitizer or switch to a real markdown renderer. Severity: critical — this is a stored XSS vector.',
 'open', 'high', 'bug', 'Tanner', 'Mason'),
('Flaky test: issue creation with labels',
 'Integration test fails roughly 1 in 20 runs locally and ~5% in CI. Suspect a race between the labels insert and the issue_labels insert. Wrapping in a transaction makes it pass 100/100 at 8 threads.',
 'open', 'medium', 'bug', 'Mason', 'Mason'),
('Login page shows flash of unstyled content',
 'The login page renders raw HTML for ~200ms before the CSS loads. Add a critical CSS inline block or preload link in the <head>. Tested on 3G throttling — the flash is very noticeable.',
 'open', 'medium', 'bug', 'Jason', 'Jordan'),
('API response times degrade above 500 concurrent requests',
 'Load testing with k6 shows P95 latency jumps from 45ms to 2.1s at 500 concurrent connections. Suspect connection pool contention — currently max 5 connections. Bumped to 20 in staging, P95 dropped to 180ms.',
 'open', 'high', 'bug', 'Riley', 'Riley'),
('Null pointer exception when user has no permissions',
 'Opening the admin panel as a read-only user causes a nil pointer dereference in the permissions resolver. Stack trace points to permission_guard.go:142.',
 'open', 'high', 'bug', 'Alex', 'Casey'),
('Search returns wrong results when query contains special characters',
 'Searching for "C++" or "C#" strips the special characters and returns irrelevant results. The search function does not URL-encode query parameters before sending to the API.',
 'open', 'medium', 'bug', 'Tanner', 'Mason'),
('Dark mode toggle resets on page navigation',
 'The dark mode toggle works on first load but resets to light mode when navigating between pages. The preference is stored in state but not persisted to localStorage.',
 'in_progress', 'medium', 'bug', 'Jordan', 'Jason'),
('Email notification double-sends on slow connections',
 'When the SMTP server responds slowly (>5s), the application retries the send before the first request completes, resulting in duplicate emails. Need an idempotency key for email jobs.',
 'open', 'medium', 'bug', 'Riley', 'Tanner'),

-- 11-20: Bugs continued
('WebSocket connection leaks under load',
 'Each WebSocket connection creates a goroutine that is not properly cleaned up when the client disconnects. After 10k connections, memory usage grows to 2GB. Need a proper ping/pong heartbeat and cleanup mechanism.',
 'open', 'high', 'bug', 'Riley', 'Mason'),
('PDF export cuts off CJK characters',
 'Exporting an issue with Chinese or Japanese text to PDF results in empty boxes instead of characters. The PDF renderer is not loading the CJK font fallback.',
 'open', 'medium', 'bug', 'Tanner', 'Alex'),
('Incorrect timezone handling in date filters',
 'Filtering issues by date uses UTC but the user interface displays local time. Filtering by "today" shows issues from tomorrow in timezones east of UTC. All datetime handling should standardize on UTC with explicit timezone info.',
 'open', 'medium', 'bug', 'Jason', 'Tanner'),
('Bulk delete operation times out for >100 items',
 'Deleting 500 issues at once triggers a 504 Gateway Timeout. The operation runs in a single transaction and locks the entire issues table. Should batch in chunks of 50 with a progress callback.',
 'open', 'medium', 'bug', 'Riley', 'Casey'),
('Avatar upload silently fails for non-image files',
 'Uploading a .pdf file to the avatar endpoint returns 200 but does not update the avatar. The server should validate Content-Type and return a descriptive error. Currently it just ignores the file and returns success.',
 'open', 'low', 'bug', 'Alex', 'Jordan'),
('Mobile sidebar menu not closable on iOS Safari',
 'On iOS Safari, the sidebar navigation drawer opens but cannot be closed by tapping the overlay. The click event does not fire on the overlay element. Works on Android Chrome and desktop.',
 'open', 'high', 'bug', 'Jordan', 'Jason'),
('Race condition in issue counter cache',
 'When two users simultaneously close the same issue, the counter cache decrements twice, going negative. Need a SELECT FOR UPDATE or optimistic locking pattern on the counter.',
 'open', 'high', 'bug', 'Mason', 'Tanner'),
('OAuth callback URL mismatch on production',
 'The OAuth redirect_uri is hardcoded to localhost:3000 in the auth provider config. On production (example.com), the callback fails with redirect_uri_mismatch. Must be configurable via environment variable.',
 'open', 'high', 'bug', 'Alex', 'Riley'),
('Drag and drop file upload not working in Firefox',
 'Dragging a file onto the upload zone works in Chrome but not in Firefox. The drop event does not fire. Investigation shows Firefox requires event.preventDefault() on both dragover and drop events.',
 'open', 'medium', 'bug', 'Jordan', 'Mason'),
('Memory leak in event stream for long-lived connections',
 'Server-Sent Events connections that stay open for more than 30 minutes accumulate memory. The event buffer is never trimmed. Each connection holds references to the last 1000 events even if the client has consumed them.',
 'open', 'high', 'bug', 'Riley', 'Tanner'),

-- 21-35: Features
('Add status filter to issue list',
 'The frontend should support filtering by open, in_progress, and closed. Filter state should live in the URL query string so links are shareable. Use useSearchParams from react-router for the source of truth.',
 'in_progress', 'medium', 'feature', 'Jason', 'Tanner'),
('Dark mode toggle persists to localStorage',
 'Add a theme toggle in the header that persists to localStorage and respects prefers-color-scheme on first visit. Should transition smoothly between themes.',
 'in_progress', 'low', 'feature', 'Jason', 'Jason'),
('Add full-text search across issue titles and descriptions',
 'Users want to search across all issues, not just filter by status. SQLite FTS5 virtual table would work. Scope to title + description for v1 — comment search can come later.',
 'open', 'medium', 'feature', 'Tanner', 'Tanner'),
('Add CSV export for issues',
 'Product wants a "Download as CSV" button on the issue list that respects current filters. Streaming response for large exports. Include all visible fields plus labels.',
 'open', 'low', 'feature', 'Alex', 'Jason'),
('Add keyboard shortcuts (j/k to navigate, c to comment)',
 'Power users want vim-style shortcuts on the issue detail page. Keep it opt-in via a settings flag. j/k to navigate the issue list, c to focus comment input, ? to show shortcut cheatsheet.',
 'open', 'low', 'feature', 'Jordan', 'Jason'),
('Real-time collaboration for issue descriptions',
 'Multiple users editing the same issue description should see each other''s changes in real-time. Use Operational Transform or CRDT via WebSocket. Start with a pilot for beta users.',
 'open', 'low', 'feature', 'Tanner', 'Riley'),
('Webhook integration for issue events',
 'Admins should be able to configure webhooks for issue.created, issue.updated, comment.created events. POST to a configurable URL with a signed payload. Include retry with exponential backoff.',
 'open', 'medium', 'feature', 'Riley', 'Tanner'),
('Sprint planning board (Kanban view)',
 'Add a Kanban board view that groups issues by status. Drag and drop to move issues between columns. Collapsible columns, WIP limits per column, and a sprint burndown chart.',
 'open', 'low', 'feature', 'Jason', 'Mason'),
('Bulk assign issues to a user',
 'Allow selecting multiple issues and assigning them all to the same user in one action. Useful for sprint planning and triage sessions. Should show a confirmation dialog with the count.',
 'open', 'low', 'feature', 'Alex', 'Casey'),
('Time tracking for issues',
 'Add start/stop timer and manual time entry on issues. Show total time spent per issue and per user. Generate a weekly timesheet report. Integrate with the CSV export.',
 'open', 'medium', 'feature', 'Mason', 'Tanner'),
('Issue templates for common workflows',
 'Allow admins to define issue templates (e.g. "Bug Report", "Feature Request", "Security Issue") with predefined fields and markdown prompts. Users can select a template when creating an issue.',
 'open', 'medium', 'feature', 'Jason', 'Jordan'),
('Comment reactions (emoji)',
 'Allow users to react to comments with emoji. Similar to GitHub reactions (thumbs up, heart, rocket, etc.). Show a count and list of who reacted. Real-time update via WebSocket.',
 'open', 'low', 'feature', 'Jordan', 'Alex'),
('Code snippet syntax highlighting in comments',
 'Auto-detect language in fenced code blocks and apply syntax highlighting. Support the top 20 programming languages. Should also render inline code with a monospace font and subtle background.',
 'open', 'low', 'feature', 'Tanner', 'Riley'),
('Watch/unwatch issues for notifications',
 'Users should be able to watch specific issues to receive notifications for all comments and status changes. Auto-watch issues created or commented on. Unwatch manually from the issue sidebar.',
 'open', 'low', 'feature', 'Alex', 'Mason'),
('Two-factor authentication',
 'Add TOTP-based two-factor authentication for all user accounts. Recovery codes (10 single-use codes) provided on setup. Optional enforcement per user role. Compatible with Google Authenticator and Authy.',
 'open', 'high', 'feature', 'Alex', 'Riley'),

-- 36-50: Features continued
('Scheduled issue reports via email',
 'Users should be able to schedule weekly/monthly CSV reports of filtered issue lists to be emailed. Configurable cron expression. PDF version for executive summaries.',
 'open', 'medium', 'feature', 'Riley', 'Casey'),
('Git branch auto-creation from issues',
 'Add a "Create branch" button on issues that creates a git branch named issue-{id}-{slug} and links the issue to the branch. Show branch name in the issue sidebar. Integrate with GitHub/GitLab API.',
 'open', 'low', 'feature', 'Tanner', 'Mason'),
('Custom fields per project',
 'Allow admins to define custom fields for issues in their project. Supported types: text, number, date, dropdown, user. Custom fields appear in the issue form and detail view automatically.',
 'open', 'medium', 'feature', 'Jason', 'Alex'),
('Sub-issues / task breakdown',
 'Allow an issue to have child issues (sub-tasks). Show a progress bar of completed sub-tasks on the parent. Drag to reorder sub-tasks. Expand/collapse in the list view.',
 'open', 'medium', 'feature', 'Mason', 'Tanner'),
('Linked issues (blocks / blocked by / relates to)',
 'Add relationships between issues: blocks, blocked by, relates to, duplicates. Show the relationship graph in the issue sidebar. Prevent circular dependencies.',
 'open', 'low', 'feature', 'Tanner', 'Riley'),
('API rate limiting with configurable tiers',
 'Implement token-bucket rate limiting per API key. Three tiers: free (60/min), pro (600/min), enterprise (unlimited). Return X-RateLimit-* headers. Graceful degradation with Retry-After.',
 'open', 'medium', 'feature', 'Riley', 'Tanner'),
('Audit log for all issue changes',
 'Track every change to issues including who made the change, what field changed, old value, new value, and timestamp. Viewable in a timeline on the issue detail page. Searchable by user and date range.',
 'open', 'medium', 'feature', 'Alex', 'Riley'),
('Markdown preview in comment editor',
 'Add a live preview tab next to the edit tab in the comment editor. Split-screen mode for side-by-side editing. Full GFM (GitHub Flavored Markdown) support including tables and task lists.',
 'in_progress', 'low', 'feature', 'Jordan', 'Jason'),
('Export single issue as PDF',
 'Add a "Print as PDF" button on the issue detail page. Generates a clean, print-friendly PDF with all comments, attachments list, and change history. Uses the browser''s native print-to-PDF for now, server-side later.',
 'open', 'low', 'feature', 'Jordan', 'Alex'),
('Dashboard with issue statistics',
 'Create a dashboard page showing: issues created per day (line chart), issues by status (pie chart), avg resolution time, top reporters, and a heatmap of activity by hour. Refresh every 60 seconds.',
 'open', 'medium', 'feature', 'Jason', 'Mason'),
('Integrate with Slack for notifications',
 'Send issue notifications to a Slack channel via Incoming Webhooks. Configurable per project. Events: issue created, status changed, @mention in comments. Include a message button to open the issue.',
 'open', 'medium', 'feature', 'Riley', 'Tanner'),
('Personalized notification digest',
 'Send a daily or weekly email digest summarizing activity on watched issues. Include: new comments, status changes, new issues matching saved filters. Link directly to each item.',
 'open', 'low', 'feature', 'Alex', 'Casey'),
('Batch label operations',
 'Allow adding or removing labels from multiple issues at once. Useful for triage sessions and sprint cleanup. Show a preview of affected issues before applying changes.',
 'open', 'low', 'feature', 'Mason', 'Jordan'),
('Issue locking for moderation',
 'Allow moderators to lock (and unlock) issues to prevent new comments. Useful for resolving heated discussions or closing a decision. Show a lock badge on locked issues. Only moderators and admins can lock.',
 'open', 'low', 'feature', 'Alex', 'Mason'),
('Mobile-responsive issue detail view',
 'The issue detail page is nearly unusable on screens narrower than 480px. Redesign the layout to stack sections vertically on mobile. Bottom sheet for metadata instead of sidebar. Touch-friendly controls.',
 'open', 'medium', 'feature', 'Jordan', 'Jason'),

-- 51-65: Tasks + Chores
('Document API key middleware',
 'README should explain the x-api-key header, the default dev key, and how to rotate it in production. Also document how to generate a secure random key.',
 'open', 'low', 'task', 'Riley', 'Mason'),
('Pagination missing on /issues endpoint',
 'GET /issues returns every row. At 10k issues this will be slow. Add ?limit and ?offset, default limit 50, max 200. Also add X-Total-Count header.',
 'closed', 'high', 'task', 'Tanner', 'Riley'),
('Migrate from SQLite to Postgres for production',
 'SQLite is great for local dev but we want WAL-replicated Postgres in production. Need to abstract the connection layer. Blocked on infra — not running Postgres until Q3.',
 'open', 'low', 'task', 'Tanner', 'Alex'),
('Remove unused legacy /v0 endpoints',
 'The /v0/issues and /v0/comments routes were superseded before public release. Nothing calls them. Confirmed via access logs over the last 90 days — zero hits.',
 'closed', 'low', 'task', 'Tanner', 'Casey'),
('Add end-to-end tests for the comment flow',
 'The comment CRUD path has no test coverage at all. Write a Playwright test that creates an issue, adds a comment, verifies it appears, then deletes it.',
 'open', 'medium', 'task', 'Jordan', 'Mason'),
('Set up CI/CD pipeline with GitHub Actions',
 'Create a GitHub Actions workflow: lint, test (with matrix: 3 Go versions), build, and deploy to staging on main branch push. Include a Docker image build and push step.',
 'open', 'medium', 'task', 'Riley', 'Tanner'),
('Add OpenAPI/Swagger documentation',
 'Document all API endpoints with OpenAPI 3.0 spec. Use swaggo annotations on handlers. Serve the spec at /api/v1/openapi.json and integrate with Swagger UI.',
 'closed', 'medium', 'task', 'Tanner', 'Riley'),
('Database migration strategy and tooling',
 'Evaluate golang-migrate vs goose vs atlas for managing database schema changes. Must support up/down migrations, version tracking, and CI integration. Document the chosen approach.',
 'open', 'low', 'task', 'Mason', 'Riley'),
('Rate limit the public API',
 'Anonymous reads currently have no rate limit. Even a generous limit (e.g. 60 req/min per IP) would prevent accidental abuse. Use a sliding window algorithm with Redis backend.',
 'open', 'medium', 'task', 'Riley', 'Jason'),
('Performance audit for list endpoint',
 'The GET /issues endpoint with 10k issues takes 800ms even with pagination. Profile the query, check for missing indexes, consider adding a covering index for the common filter paths.',
 'open', 'medium', 'task', 'Mason', 'Riley'),
('Upgrade chi router to v5',
 'We are still on chi v4. v5 has breaking changes to middleware signatures. Create a migration guide and test all routes after upgrade. Key benefit: better route compatibility with Go 1.22+.',
 'in_progress', 'low', 'task', 'Tanner', 'Riley'),
('Set up structured logging with slog',
 'Replace the current ad-hoc logging with Go 1.21 slog. All logs should be structured JSON in production, human-readable text in dev. Include request_id, user, and duration in every log line.',
 'closed', 'medium', 'task', 'Riley', 'Tanner'),
('Add health check endpoint with dependency checks',
 'The /health endpoint should return the status of database connectivity, Redis (if used), and background worker pool. Return 200 if all healthy, 503 if degraded with details on what failed.',
 'in_progress', 'medium', 'task', 'Riley', 'Tanner'),
('Create Docker Compose setup for local development',
 'Add a docker-compose.yml with: Go API server (hot-reload with air), SQLite (or Postgres for parity), Redis for caching, and Mailhog for email testing. Single docker compose up for new contributors.',
 'open', 'low', 'task', 'Riley', 'Casey'),
('Implement graceful shutdown for background workers',
 'The worker pool currently hard-exits on SIGTERM, potentially losing in-flight jobs. Implement a proper shutdown: stop accepting new jobs, wait for running jobs (with timeout), then exit.',
 'open', 'medium', 'task', 'Riley', 'Tanner'),

-- 66-80: Questions + Discussion
('Should attachments be deleted when closing an issue?',
 'Need a product decision before implementing cleanup behavior. Options: (a) keep forever, (b) delete on close, (c) soft-delete with 30-day grace. Decision: keep attachments after close; delete only when issue is deleted.',
 'closed', 'medium', 'question', 'Alex', 'Jason'),
('What is the target response time SLA?',
 'Before we invest more in performance optimization, we need to agree on targets. Proposed: p50 < 100ms, p95 < 500ms, p99 < 2s for the main CRUD endpoints. File uploads exempted. Discuss in the next engineering sync.',
 'open', 'low', 'question', 'Riley', 'Tanner'),
('How should we handle soft deletes?',
 'Add a deleted_at column approach across all entities? Or use a separate archive table? Considerations: query performance (WHERE deleted_at IS NULL everywhere), data recovery, GDPR compliance (right to erasure).',
 'open', 'medium', 'question', 'Mason', 'Casey'),
('Should we adopt GraphQL for the next API version?',
 'The frontend team is requesting a GraphQL endpoint to reduce over-fetching. Proposal: add a GraphQL gateway alongside the REST API, migrate incrementally. Concerns: caching complexity, learning curve, tooling maturity.',
 'open', 'low', 'question', 'Jason', 'Tanner'),
('What is the strategy for handling file uploads in production?',
 'Currently files are stored on local disk. For horizontal scaling we need: (a) S3-compatible object storage, (b) direct-to-S3 upload presigned URLs, (c) CDN for public attachments. Evaluate MinIO for self-hosted option.',
 'open', 'medium', 'question', 'Riley', 'Alex'),
('Should we use UUID or auto-increment IDs in the API?',
 'Auto-increment IDs leak information (issue count, growth rate). UUIDs are better for security and distributed systems. But UUIDs are bulkier in indexes. Compromise: use UUID v7 (time-ordered) for external IDs, auto-increment internally.',
 'open', 'low', 'question', 'Tanner', 'Riley'),
('How to handle timezones across the application?',
 'Current approach: store UTC, display in user timezone. But reporting and filtering (e.g. "issues created today") break across timezone boundaries. Proposal: add a timezone field to user profiles, all server-side date math in UTC.',
 'open', 'medium', 'question', 'Jason', 'Mason'),
('When should we start charging for the API?',
 'Usage is growing 15% MoM. Current hosting costs: $800/mo. At current trajectory we hit $3000/mo in 6 months. Options: (a) free tier with rate limits, (b) usage-based billing, (c) feature-tiered plans.',
 'open', 'low', 'question', 'Alex', 'Casey'),
('Should we containerize the development environment?',
 'New contributors spend 2-3 hours setting up their environment. A devcontainer or Docker Compose setup would reduce this to 10 minutes. Downside: macOS Docker perf is poor for file watching. Use devcontainer for Linux/WSL, native for macOS.',
 'open', 'medium', 'question', 'Riley', 'Tanner'),
('What monitoring stack should we adopt?',
 'Options: (a) Grafana + Prometheus + Loki, (b) Datadog (paid), (c) Sentry for errors + Grafana for metrics. We already use Sentry for frontend errors. Proposal: extend Sentry to backend, add Prometheus for custom metrics.',
 'open', 'medium', 'question', 'Riley', 'Mason'),
('How to structure a microservices migration?',
 'Monolith is at 50k LOC. Extraction candidates: (a) auth service, (b) notification service, (c) file storage service. Strategy: Strangler Fig pattern — add new features as services, gradually migrate old ones. Timeline: 9-12 months.',
 'open', 'low', 'question', 'Tanner', 'Riley'),
('Should we implement a feature flag system?',
 'Deploying unfinished features to production is risky. A feature flag system would allow: phased rollouts, A/B testing, instant kill switches. Evaluate: LaunchDarkly (SaaS) vs Flagsmith (self-hosted) vs custom (Redis-based).',
 'open', 'medium', 'question', 'Jason', 'Alex'),
('What is our data retention policy?',
 'Legal requires a formal data retention policy. Proposal: issue data retained indefinitely, deleted issues soft-deleted for 90 days then purged, audit logs retained 12 months, session data 30 days. Document in the security policy.',
 'open', 'low', 'question', 'Alex', 'Casey'),
('How to approach accessibility compliance?',
 'We need to meet WCAG 2.1 AA standards for enterprise contracts. Current gaps: keyboard navigation, screen reader labels, color contrast ratios. Plan: audit with axe-core, fix critical issues, add accessibility tests to CI.',
 'open', 'medium', 'question', 'Jordan', 'Jason'),
('Should we support SAML SSO for enterprise customers?',
 'Three enterprise prospects have requested SAML SSO. Implementation estimate: 2-3 weeks for basic SAML, plus 1 week per IdP (Okta, Azure AD, OneLogin) for testing. Proposed: implement generic SAML, charge for IdP-specific certifications.',
 'open', 'medium', 'question', 'Alex', 'Riley'),

-- 81-100: More bugs + features
('Infinite redirect loop when session expires',
 'When the session expires during a form submission, the login redirect sets a return_to parameter, but the login page itself triggers a redirect loop because it checks authentication. Fix: exempt the login page from auth check.',
 'open', 'high', 'bug', 'Alex', 'Jason'),
('Notification badge count not updating in real-time',
 'The notification bell icon shows a badge with unread count, but it only updates on page load. Polling every 30 seconds or use Server-Sent Events for real-time updates. SSE is preferred to avoid HTTP overhead.',
 'in_progress', 'medium', 'bug', 'Jordan', 'Mason'),
('Image optimization pipeline timeout',
 'Uploading a 20MB image triggers the image optimization pipeline (resize to thumbnails + WebP conversion), which times out after 30 seconds. Move image processing to a background job queue with a proper timeout of 5 minutes.',
 'open', 'medium', 'bug', 'Riley', 'Tanner'),
('Auto-save draft not triggering for new users',
 'The auto-save feature creates a draft but does not handle the case where the user has no existing draft. The API returns 404, which the UI treats as an error instead of creating a new draft.',
 'open', 'low', 'bug', 'Jordan', 'Alex'),
('Pagination total count inaccurate with filters',
 'When filtering by status and search simultaneously, the total count in the pagination response is incorrect. The COUNT query is not applying the same WHERE clause as the data query.',
 'open', 'medium', 'bug', 'Tanner', 'Mason'),
('Date picker shows wrong month on mobile',
 'The date picker component initializes to the current month on desktop but shows January 1970 on iOS Safari. Root cause: the component receives an undefined date prop and Date() constructor interprets it differently on WebKit.',
 'open', 'medium', 'bug', 'Jordan', 'Jason'),
('Webhook signature verification fails for non-ASCII payloads',
 'When the webhook payload contains non-ASCII characters (e.g. emoji, CJK text), the HMAC-SHA256 signature verification fails. The webhook sender is URL-encoding the payload before signing, but the receiver is not decoding before verification.',
 'open', 'high', 'bug', 'Riley', 'Tanner'),
('Session cookie SameSite attribute too restrictive',
 'Setting SameSite=Strict on the session cookie breaks the OAuth flow because the callback from the identity provider is treated as a cross-site request. Changed to SameSite=Lax for OAuth routes.',
 'closed', 'high', 'bug', 'Alex', 'Riley'),
('Long issue title breaks layout on mobile',
 'A title with 200 characters without spaces overflows the issue card on mobile viewports. Add CSS word-break: break-word and a max-height with ellipsis for the list view.',
 'open', 'low', 'bug', 'Jordan', 'Tanner'),
('API key permissions not checked for batch operations',
 'The bulk assign and bulk label endpoints do not check if the API key has write permissions. A read-only key can modify issues via these endpoints. Need to add permission checks before processing each item in the batch.',
 'open', 'high', 'bug', 'Alex', 'Riley'),
('Rate limiter key collision for anonymous users',
 'The rate limiter uses IP address as the key, but users behind a corporate NAT all share the same IP. This means one user hitting the rate limit blocks the entire office. Solution: use X-Forwarded-For + a salt.',
 'in_progress', 'medium', 'bug', 'Riley', 'Tanner'),
('GraphQL resolver N+1 query in issue list',
 'The GraphQL endpoint for listing issues has an N+1 problem: it queries the database once for the issues, then once for each issue''s labels. For 50 issues, that is 51 queries. Fixed with dataloader pattern.',
 'open', 'medium', 'bug', 'Tanner', 'Mason'),
('Scroll position lost after navigating back to issue list',
 'When clicking an issue, then pressing the browser back button, the scroll position in the issue list is lost and resets to the top. Need to restore scroll position from history.state.',
 'open', 'low', 'bug', 'Jordan', 'Jason'),
('File upload progress bar stuck at 99%',
 'The upload progress bar reaches 99% and stays there for 10-15 seconds before completing. The progress event fires on chunk upload, but the final chunk does not trigger the 100% callback until server processing finishes.',
 'open', 'medium', 'bug', 'Jordan', 'Mason'),
('LDAP group sync creates duplicate memberships',
 'The LDAP sync job runs hourly and adds group memberships but does not check if they already exist. Running the sync twice creates duplicate entries in the user_groups table. Fix: use INSERT OR IGNORE or check existence first.',
 'open', 'medium', 'bug', 'Alex', 'Riley'),
('Email template not rendering in Outlook',
 'The HTML email templates use modern CSS (flexbox, custom properties) that Outlook does not support. Emails render as plain text on Outlook desktop. Need to use table-based layouts and inline styles for email compatibility.',
 'open', 'medium', 'bug', 'Jason', 'Tanner'),
('Database migration fails on empty schema',
 'Running the initial migration on a fresh database fails because the IF NOT EXISTS clause is missing on some CREATE TABLE statements. The migration script was written assuming an existing schema from v1.',
 'closed', 'high', 'bug', 'Mason', 'Tanner'),
('User mention autocomplete shows deactivated users',
 'Typing @ in a comment shows deactivated/disabled users in the autocomplete dropdown. Filter out users where active=false and add a "(deactivated)" label if the mentioned user was deactivated after the comment.',
 'open', 'low', 'bug', 'Jordan', 'Alex'),
('Windows path separator breaks file uploads on server',
 'Uploading a file from Windows sends backslashes in the filename. The server stores the file with backslashes, which breaks the download URL. Sanitize filenames to replace backslashes with underscores.',
 'closed', 'medium', 'bug', 'Tanner', 'Casey'),
('Import CSV silently drops rows with missing fields',
 'Importing issues from a CSV file silently drops rows that are missing required fields. The import process should validate each row, collect errors, and report them to the user in a structured format.',
 'open', 'medium', 'bug', 'Mason', 'Tanner'),

-- 101-110: Final batch
('SSH key rotation automation',
 'Developer SSH keys expire every 90 days. Currently the process is manual. Automate key rotation with a self-service page where developers upload new keys, and an audit log of key changes.',
 'open', 'low', 'task', 'Riley', 'Alex'),
('API versioning strategy',
 'Decide on API versioning approach: URL path (/v1/ vs /v2/), header (Accept: application/vnd.api+json;version=2), or query parameter (?api_version=2). We are leaning towards header-based versioning for cleaner URLs.',
 'open', 'low', 'question', 'Tanner', 'Riley'),
('Automate dependency updates with Dependabot',
 'Configure Dependabot to automatically create PRs for outdated dependencies. Rules: (a) patch versions auto-merge if tests pass, (b) minor versions create PR for review, (c) major versions require manual review.',
 'open', 'low', 'task', 'Riley', 'Mason'),
('Add rate limiting to the login endpoint',
 'The /auth/login endpoint has no rate limiting, making it vulnerable to brute force attacks. Implement: 5 attempts per minute per IP, 10 attempts per minute per username. Return 429 with Retry-After header.',
 'open', 'high', 'feature', 'Alex', 'Riley'),
('Error tracking dashboard for ops team',
 'Create a dashboard showing: error rate by endpoint, top 5 errors by frequency, error rate trend (7-day), and affected users count. Based on structured error logging + Prometheus metrics.',
 'open', 'medium', 'feature', 'Riley', 'Tanner'),
('Search should support partial word matching',
 'Current search requires an exact word match. Searching for "docu" should match "documentation". Implement prefix-based matching with SQLite LIKE, or migrate to FTS5 for better performance and relevance ranking.',
 'open', 'medium', 'feature', 'Tanner', 'Mason'),
('Issue cloning (copy with new ID)',
 'Users frequently create very similar issues. Add a "Clone issue" button that copies all fields (title, description, labels) into a new issue. The cloned issue should link back to the original.',
 'open', 'low', 'feature', 'Jason', 'Tanner'),
('Custom status workflow per project',
 'Different teams need different issue workflows. Allow admins to define custom statuses and transitions (e.g. "Needs Review" → "Approved" → "In Development"). Visual workflow editor in settings.',
 'open', 'medium', 'feature', 'Jason', 'Mason'),
('Self-service data export for GDPR compliance',
 'Users must be able to export all their personal data (comments, created issues, profile) in a machine-readable format (JSON). Triggered from the user settings page. Email a download link when ready.',
 'open', 'medium', 'feature', 'Alex', 'Riley'),
('Merge duplicate issues',
 'Two or more issues about the same topic can be merged. The merged issue keeps one title/description and combines all comments, labels, and attachments. The merged issues become "duplicate" and link to the target.',
 'open', 'low', 'feature', 'Mason', 'Tanner');

-- ── Comments (200+) ─────────────────────────────────────────────────────────
INSERT INTO comments (issue_id, author, body) VALUES
    -- Issue 1
    (1, 'Tanner', 'Start by checking the request body limit and multipart extractor errors.'),
    (1, 'Jason', 'The frontend should also display file size before upload so users know it will fail.'),
    (1, 'Riley', 'Default axum body limit is 2MB. We need DefaultBodyLimit::max(10 * 1024 * 1024) on the router.'),
    (1, 'Tanner', 'Pushed a draft. Returns 413 with JSON body now. Need a test for the boundary case.'),
    (1, 'Mason', 'Tested with 6MB file — got clear 413. Boundary test with 10MB exactly works. Ship it.'),
    -- Issue 2
    (2, 'Tanner', 'Confirmed: the query is SELECT * FROM comments WHERE issue_id = ?. No ORDER BY.'),
    (2, 'Mason', 'Add ORDER BY created_at ASC, id ASC — the id tiebreaker matters if two comments land in the same second.'),
    (2, 'Riley', 'Is this something we could fix in the ORM layer globally instead of per-query?'),
    -- Issue 3
    (3, 'Mason', 'This is bad — please prioritize. I can take it if Tanner is busy.'),
    (3, 'Tanner', 'Taking it. Switching to react-markdown with default escaping; removing dangerouslySetInnerHTML.'),
    (3, 'Alex', 'Product sign-off: markdown rendering is fine. Do not ship a WYSIWYG.'),
    (3, 'Mason', 'Confirmed fix: XSS vector closed. Added a test case with script injection.'),
    -- Issue 4
    (4, 'Mason', 'Reproduced once locally by running cargo test --test-threads=8. Single-threaded run has not failed yet.'),
    (4, 'Mason', 'Wrapping the two inserts in a transaction makes it pass 100/100 runs at 8 threads. PR incoming.'),
    (4, 'Riley', 'Also added a test for the exact race condition scenario. Good catch.'),
    -- Issue 5
    (5, 'Jordan', 'I think we need the CSS preload approach. Critical inline is hard to maintain.'),
    (5, 'Jason', 'Preload link in <head> it is. Will test on 3G throttling to confirm.'),
    (5, 'Jordan', 'Tested on 3G — flash is gone. Preload approach works well.'),
    -- Issue 6
    (6, 'Riley', 'Load test results attached. The bottleneck is clearly the pool — 5 connections queue behind each other.'),
    (6, 'Tanner', 'Bumped to 20 in staging. P95 dropped to 180ms. Will set max_connections via env var so ops can tune it.'),
    (6, 'Riley', 'Final config: max_connections=25, pool_timeout=5s. Documented in the ops runbook.'),
    -- Issue 10
    (10, 'Riley', 'SMTP timeout is currently 3s. Increasing to 10s and adding idempotency key column to email_queue table.'),
    (10, 'Tanner', 'Idempotency key should be a hash of (recipient, subject, body) so the same email is not sent twice.'),
    -- Issue 11
    (11, 'Riley', 'goroutine count grows linearly with WebSocket connections. Added a ConnTracker with cleanup on disconnect.'),
    (11, 'Mason', 'Also added a /debug/ws endpoint to inspect active connections. Useful for ops.'),
    -- Issue 13
    (13, 'Jason', 'Root cause: Go time.Time marshals to RFC3339 without timezone offset info in some contexts.'),
    (13, 'Tanner', 'Fixed: always store as UTC, format with .Format(time.RFC3339) before sending to client.'),
    -- Issue 16
    (16, 'Jordan', 'Sidebar issue reproduced on iPhone 13 Pro iOS 17.2. The overlay div has pointer-events: none.'),
    (16, 'Jason', 'Fix: pointer-events: auto on the overlay. Also added a close (X) button for clarity.'),
    -- Issue 17
    (17, 'Mason', 'Optimistic locking approach: UPDATE issues SET counter = counter - 1 WHERE id = ? AND counter > 0.'),
    (17, 'Tanner', 'Plus a CHECK constraint on the counter column. Double safety.'),
    -- Issue 20
    (20, 'Riley', 'SSE event buffer is an in-memory ring buffer capped at 1000. Added a TTL of 5 minutes per event.'),
    (20, 'Tanner', 'Consider switching to Redis pub/sub for horizontal scaling of SSE.'),
    -- Issue 21
    (21, 'Mason', 'Use query params so URLs are shareable.'),
    (21, 'Jason', 'Agreed. I will use useSearchParams from react-router for the source of truth.'),
    (21, 'Mason', 'Also added a "Copy link to this view" button next to the filter bar.'),
    -- Issue 22
    (22, 'Jason', 'Using CSS custom properties for themes. All color references use var(--color-bg) etc.'),
    (22, 'Jordan', 'Tested with prefers-color-scheme: dark. Works on first visit. localStorage persistence tested.'),
    -- Issue 23
    (23, 'Tanner', 'I would scope this to title + description for v1. Comment search can come later — it bloats the index significantly.'),
    (23, 'Alex', 'Agreed. Also want to make sure FTS does not break when we eventually move to Postgres.'),
    (23, 'Riley', 'FTS5 on SQLite maps poorly to Postgres tsvector. Budget a rewrite when we migrate.'),
    -- Issue 28
    (28, 'Jason', 'Kanban view will replace the current list view as the default. List view will remain as an option.'),
    (28, 'Riley', 'WIP limits: configurable per column. Defaults: ToDo=10, InProgress=5, Review=3.'),
    -- Issue 33
    (33, 'Tanner', 'Using highlight.js with auto-detect. Added 20 most common languages. Bundle size impact: +45KB gzipped.'),
    (33, 'Jordan', 'Can we lazy-load language packs? Only load the languages actually used in the project.'),
    -- Issue 34
    (34, 'Alex', 'Notifications: email + in-app + optional Slack. User preferences stored in notification_settings table.'),
    (34, 'Jason', 'What about push notifications for mobile? We should plan for this.'),
    -- Issue 35
    (35, 'Alex', 'TOTP implementation using github.com/pquerna/otp. Recovery codes are bcrypt-hashed before storage.'),
    (35, 'Riley', 'Tested with Google Authenticator and Authy. Both work. Also added a "Verify setup" step before enabling.'),
    -- Issue 36
    (36, 'Riley', 'Scheduled reports use cron syntax. Implemented with robfig/cron library. Reports generated as CSV.'),
    (36, 'Casey', 'Can we also support PDF for executive summaries? Using wkhtmltopdf or a Go PDF library.'),
    -- Issue 40
    (40, 'Tanner', 'Relationship types: blocks, blocked_by, relates_to, duplicates, cloned_from.'),
    (40, 'Riley', 'Added a visual graph in the issue sidebar using vis-network.'),
    -- Issue 41
    (41, 'Riley', 'Token bucket implementation using golang.org/x/time/rate. Three tiers configured in the billing service.'),
    (41, 'Tanner', 'Rate limit headers: X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset.'),
    -- Issue 42
    (42, 'Alex', 'Audit log table: id, action, entity_type, entity_id, actor_id, changes (JSON), created_at.'),
    (42, 'Riley', 'Index on (entity_type, entity_id) for fast lookups. Index on (actor_id) for user audit trail.'),
    -- Issue 43
    (43, 'Jordan', 'Split-pane editor implemented with CodeMirror 6 for the edit pane and a rendered preview pane.'),
    (43, 'Tanner', 'Added support for task lists with checkboxes. The checkbox state is stored in the comment metadata.'),
    -- Issue 45
    (45, 'Jason', 'Dashboard metrics powered by a materialized view refreshed every 5 minutes.'),
    (45, 'Riley', 'Performance note: the daily-created chart query went from 2s to 30ms after adding the index on issues.created_at.'),
    -- Issue 47
    (47, 'Alex', 'Email digest: daily at 8am in user''s timezone. Powered by a cron job that queries the notification_queue table.'),
    (47, 'Casey', 'Add an unsubscribe link in the email footer. Required for legal compliance.'),
    -- Issue 48
    (48, 'Mason', 'Batch label operations: confirm dialog shows "This will affect 15 issues. Are you sure?"'),
    (48, 'Jordan', 'Added undo button with a 5-second delay before applying. Uses a simple job queue.'),
    -- Issue 49
    (49, 'Alex', 'Locked issues show a "🔒 Locked" badge. Only moderators can comment. Existing comments remain visible.'),
    (49, 'Mason', 'Also added an unlock with reason field — logged to audit log for transparency.'),
    -- Issue 50
    (50, 'Jordan', 'Mobile layout: sidebar becomes a bottom sheet. Metadata shown in a collapsible accordion.'),
    (50, 'Jason', 'Tested on iPhone SE (375px width). All sections stack vertically and are usable.'),
    -- Issue 55
    (55, 'Jordan', 'Writing the Playwright test now. API tests already exist in test_api.sh but nothing for the browser flow.'),
    (55, 'Mason', 'Make sure to test the empty state — creating the first comment on an issue should not crash.'),
    -- Issue 56
    (56, 'Riley', 'CI pipeline: lint (golangci-lint), test (3 Go versions: 1.21, 1.22, 1.23), build and push Docker image.'),
    (56, 'Tanner', 'Cache Go module downloads between runs. Cuts CI time from 4min to 45s.'),
    -- Issue 65
    (65, 'Riley', 'Worker shutdown: context.WithTimeout(10s). Running jobs get the cancel signal, cleanup, then exit.'),
    (65, 'Tanner', 'Added a /health/workers endpoint showing: active, queued, completed, failed job counts.'),
    -- Issue 66
    (66, 'Alex', 'Keep attachments after close; delete only when issue is deleted. Decision logged.'),
    (66, 'Jason', 'Sounds right. Closing this and opening a separate task for the deletion cascade test.'),
    -- Issue 73
    (73, 'Alex', 'Free tier: 5 projects, 500 issues, 1GB storage. Pro: unlimited, $29/user/mo. Enterprise: custom.'),
    (73, 'Riley', 'Usage-based billing: $0.001 per API call after free tier. Implemented with Stripe metered billing.'),
    -- Issue 80
    (80, 'Alex', 'SAML implementation: using crewjam/saml library. Supports HTTP-POST and HTTP-Redirect bindings.'),
    (80, 'Riley', 'Tested with Okta and Azure AD. OneLogin tested by customer. All passing.'),
    -- Issue 81
    (81, 'Alex', 'Root cause: the auth middleware checks session before the route matches. Login page should skip auth check.'),
    (81, 'Jason', 'Fix: add login and callback URLs to the public routes whitelist in the middleware.'),
    -- Issue 82
    (82, 'Jordan', 'SSE endpoint at /api/notifications/stream. Falls back to polling every 30s if SSE is not supported.'),
    (82, 'Mason', 'Tested with 100 concurrent SSE connections. Memory usage: +15MB total. Acceptable.'),
    -- Issue 86
    (86, 'Jordan', 'Date picker issue: the value prop is not set on initial render, causing Date() to use epoch.'),
    (86, 'Jason', 'Fix: initialize date to new Date() if value is undefined. Added a regression test.'),
    -- Issue 89
    (89, 'Jordan', 'Long title fix: CSS word-break: break-word + text-overflow: ellipsis on the list card.'),
    (89, 'Jason', 'Also added a tooltip on hover showing the full title.'),
    -- Issue 91
    (91, 'Riley', 'Rate limiter fix: use X-Forwarded-For first, fall back to RemoteAddr. Added X-Real-IP as third option.'),
    (91, 'Tanner', 'Also added a configurable rate limit key prefix for multi-tenant deployments.'),
    -- Issue 92
    (92, 'Tanner', 'Dataloader implemented with github.com/graph-gophers/dataloader. Batch function groups labels by issue_id.'),
    (92, 'Mason', 'Before: 51 queries for 50 issues. After: 2 queries (issues + labels). 96% reduction.'),
    -- Issue 100
    (100, 'Mason', 'CSV validation: each row validated against required fields. Errors collected and reported as a JSON array.'),
    (100, 'Tanner', 'Also added a preview mode: import dry-run that shows how many rows will be imported and what errors exist.');

-- ── Issue-Label Associations ─────────────────────────────────────────────────
INSERT INTO issue_labels (issue_id, label_id) VALUES
    (1, 1), (1, 3),
    (2, 1), (2, 3),
    (3, 12), (3, 3),
    (4, 11), (4, 3),
    (5, 10), (5, 3), (5, 2),
    (6, 8), (6, 1),
    (7, 13), (7, 12),
    (8, 1), (8, 3),
    (9, 10), (9, 2), (9, 3),
    (10, 8), (10, 1),
    (11, 8), (11, 3),
    (12, 10), (12, 3),
    (13, 1), (13, 3),
    (14, 8), (14, 1),
    (15, 10), (15, 2),
    (16, 18), (16, 2), (16, 3),
    (17, 6), (17, 3),
    (18, 7), (18, 12), (18, 3),
    (19, 2), (19, 3),
    (20, 8), (20, 3),
    (21, 2), (21, 4),
    (22, 10), (22, 2),
    (23, 1), (23, 6),
    (24, 2), (24, 4),
    (25, 10), (25, 16),
    (26, 13), (26, 2),
    (27, 1), (27, 15),
    (28, 2), (28, 10),
    (29, 2), (29, 16),
    (30, 6), (30, 2),
    (31, 2), (31, 16),
    (32, 10), (32, 16), (32, 2),
    (33, 2), (33, 10),
    (34, 2), (34, 16),
    (35, 7), (35, 12),
    (36, 2), (36, 1),
    (37, 15), (37, 1),
    (38, 2), (38, 6),
    (39, 2), (39, 4),
    (40, 2), (40, 6),
    (41, 1), (41, 8),
    (42, 6), (42, 12),
    (43, 2), (43, 10),
    (44, 2), (44, 10),
    (45, 2), (45, 6),
    (46, 1), (46, 15),
    (47, 1), (47, 16),
    (48, 2), (48, 16),
    (49, 13), (49, 12),
    (50, 18), (50, 16), (50, 2),
    (51, 9), (51, 1),
    (52, 1), (52, 8),
    (53, 6), (53, 13),
    (54, 1),
    (55, 11), (55, 4),
    (56, 15), (56, 11),
    (57, 9), (57, 1),
    (58, 6), (58, 15),
    (59, 8), (59, 12),
    (60, 8), (60, 6),
    (61, 13), (61, 15),
    (62, 15), (62, 11),
    (63, 15), (63, 9),
    (64, 15), (64, 4),
    (65, 13), (65, 8),
    (66, 5), (66, 13),
    (67, 8), (67, 5),
    (68, 6), (68, 5),
    (69, 1), (69, 5),
    (70, 15), (70, 6),
    (71, 1), (71, 5),
    (72, 6), (72, 5),
    (73, 2), (73, 5),
    (74, 15), (74, 5),
    (75, 15), (75, 11),
    (76, 1), (76, 5),
    (77, 2), (77, 15),
    (78, 12), (78, 5),
    (79, 18), (79, 19),
    (80, 7), (80, 5),
    (81, 7), (81, 3),
    (82, 16), (82, 2),
    (83, 8), (83, 3),
    (84, 3), (84, 2),
    (85, 1), (85, 3),
    (86, 18), (86, 3), (86, 2),
    (87, 1), (87, 3),
    (88, 7), (88, 12),
    (89, 2), (89, 10), (89, 3),
    (90, 7), (90, 12), (90, 3),
    (91, 1), (91, 8), (91, 3),
    (92, 6), (92, 8),
    (93, 2), (93, 3),
    (94, 2), (94, 8),
    (95, 6), (95, 15),
    (96, 2), (96, 10),
    (97, 3), (97, 6),
    (98, 20), (98, 2),
    (99, 19), (99, 6),
    (100, 11), (100, 6),
    (101, 15), (101, 20),
    (102, 1), (102, 5),
    (103, 15), (103, 20),
    (104, 7), (104, 12),
    (105, 15), (105, 8),
    (106, 6), (106, 1),
    (107, 2), (107, 4),
    (108, 2), (108, 6),
    (109, 7), (109, 12),
    (110, 6), (110, 2);
